export const display = [
    { name: "Abril Fatface", value: "'Abril Fatface', cursive" },
    { name: "Akaya Kanadaka", value: "'Akaya Kanadaka', cursive" },
    { name: "Akaya Telivigala", value: "'Akaya Telivigala', cursive" },
    { name: "Akronim", value: "'Akronim', cursive" },
    { name: "Alfa Slab One", value: "'Alfa Slab One', cursive" },
    { name: "Allan", value: "'Allan', cursive" },
    { name: "Almendra Display", value: "'Almendra Display', cursive" },
    { name: "Amarante", value: "'Amarante', cursive" },
    { name: "Arbutus", value: "'Arbutus', cursive" },
    { name: "Arima Madurai", value: "'Arima Madurai', cursive" },
    { name: "Asset", value: "'Asset', cursive" },
    { name: "Astloch", value: "'Astloch', cursive" },
    { name: "Atma", value: "'Atma', cursive" },
    { name: "Atomic Age", value: "'Atomic Age', cursive" },
    { name: "Aubrey", value: "'Aubrey', cursive" },
    { name: "Audiowide", value: "'Audiowide', cursive" },
    { name: "Autour One", value: "'Autour One', cursive" },
    { name: "Averia Gruesa Libre", value: "'Averia Gruesa Libre', cursive" },
    { name: "Averia Libre", value: "'Averia Libre', cursive" },
    { name: "Averia Sans Libre", value: "'Averia Sans Libre', cursive" },
    { name: "Averia Serif Libre", value: "'Averia Serif Libre', cursive" },
    { name: "Bahiana", value: "'Bahiana', cursive" },
    { name: "Bahianita", value: "'Bahianita', cursive" },
    { name: "Baloo 2", value: "'Baloo 2', cursive" },
    { name: "Baloo Bhai 2", value: "'Baloo Bhai 2', cursive" },
    { name: "Baloo Bhaina 2", value: "'Baloo Bhaina 2', cursive" },
    { name: "Baloo Chettan 2", value: "'Baloo Chettan 2', cursive" },
    { name: "Baloo Da 2", value: "'Baloo Da 2', cursive" },
    { name: "Baloo Paaji 2", value: "'Baloo Paaji 2', cursive" },
    { name: "Baloo Tamma 2", value: "'Baloo Tamma 2', cursive" },
    { name: "Baloo Tammudu 2", value: "'Baloo Tammudu 2', cursive" },
    { name: "Baloo Thambi 2", value: "'Baloo Thambi 2', cursive" },
    { name: "Balsamiq Sans", value: "'Balsamiq Sans', cursive" },
    { name: "Bangers", value: "'Bangers', cursive" },
    { name: "Barriecito", value: "'Barriecito', cursive" },
    { name: "Barrio", value: "'Barrio', cursive" },
    { name: "Baumans", value: "'Baumans', cursive" },
    { name: "Bebas Neue", value: "'Bebas Neue', cursive" },
    { name: "Bellota", value: "'Bellota', cursive" },
    { name: "Bellota Text", value: "'Bellota Text', cursive" },
    { name: "Bevan", value: "'Bevan', cursive" },
    {
        name: "Big Shoulders Display",
        value: "'Big Shoulders Display', cursive",
    },
    {
        name: "Big Shoulders Inline Display",
        value: "'Big Shoulders Inline Display', display",
    },
    {
        name: "Big Shoulders Inline Text",
        value: "'Big Shoulders Inline Text', display",
    },
    {
        name: "Big Shoulders Stencil Display",
        value: "'Big Shoulders Stencil Display', display",
    },
    {
        name: "Big Shoulders Stencil Text",
        value: "'Big Shoulders Stencil Text', display",
    },
    { name: "Big Shoulders Text", value: "'Big Shoulders Text', cursive" },
    { name: "Bigelow Rules", value: "'Bigelow Rules', cursive" },
    { name: "Bigshot One", value: "'Bigshot One', cursive" },
    { name: "Black Ops One", value: "'Black Ops One', cursive" },
    { name: "Boogaloo", value: "'Boogaloo', cursive" },
    { name: "Bowlby One", value: "'Bowlby One', cursive" },
    { name: "Bowlby One SC", value: "'Bowlby One SC', cursive" },
    { name: "Bubblegum Sans", value: "'Bubblegum Sans', cursive" },
    { name: "Bungee", value: "'Bungee', cursive" },
    { name: "Bungee Hairline", value: "'Bungee Hairline', cursive" },
    { name: "Bungee Inline", value: "'Bungee Inline', cursive" },
    { name: "Bungee Outline", value: "'Bungee Outline', cursive" },
    { name: "Bungee Shade", value: "'Bungee Shade', cursive" },
    { name: "Butcherman", value: "'Butcherman', cursive" },
    { name: "Cabin Sketch", value: "'Cabin Sketch', cursive" },
    { name: "Caesar Dressing", value: "'Caesar Dressing', cursive" },
    { name: "Calistoga", value: "'Calistoga', cursive" },
    { name: "Carter One", value: "'Carter One', cursive" },
    { name: "Ceviche One", value: "'Ceviche One', cursive" },
    { name: "Changa One", value: "'Changa One', cursive" },
    { name: "Chango", value: "'Chango', cursive" },
    { name: "Chela One", value: "'Chela One', cursive" },
    { name: "Chelsea Market", value: "'Chelsea Market', cursive" },
    { name: "Cherry Cream Soda", value: "'Cherry Cream Soda', cursive" },
    { name: "Cherry Swash", value: "'Cherry Swash', cursive" },
    { name: "Chewy", value: "'Chewy', cursive" },
    { name: "Chicle", value: "'Chicle', cursive" },
    { name: "Chonburi", value: "'Chonburi', cursive" },
    { name: "Cinzel Decorative", value: "'Cinzel Decorative', cursive" },
    { name: "Coda", value: "'Coda', cursive" },
    { name: "Codystar", value: "'Codystar', cursive" },
    { name: "Coiny", value: "'Coiny', cursive" },
    { name: "Combo", value: "'Combo', cursive" },
    { name: "Comfortaa", value: "'Comfortaa', cursive" },
    { name: "Concert One", value: "'Concert One', cursive" },
    { name: "Contrail One", value: "'Contrail One', cursive" },
    { name: "Corben", value: "'Corben', cursive" },
    { name: "Creepster", value: "'Creepster', cursive" },
    { name: "Croissant One", value: "'Croissant One', cursive" },
    { name: "Crushed", value: "'Crushed', cursive" },
    { name: "Cute Font", value: "'Cute Font', cursive" },
    { name: "Diplomata", value: "'Diplomata', cursive" },
    { name: "Diplomata SC", value: "'Diplomata SC', cursive" },
    { name: "Dynalight", value: "'Dynalight', cursive" },
    { name: "Eater", value: "'Eater', cursive" },
    { name: "Elsie", value: "'Elsie', cursive" },
    { name: "Elsie Swash Caps", value: "'Elsie Swash Caps', cursive" },
    { name: "Emblema One", value: "'Emblema One', cursive" },
    { name: "Emilys Candy", value: "'Emilys Candy', cursive" },
    { name: "Erica One", value: "'Erica One', cursive" },
    { name: "Ewert", value: "'Ewert', cursive" },
    { name: "Expletus Sans", value: "'Expletus Sans', cursive" },
    { name: "Farsan", value: "'Farsan', cursive" },
    { name: "Fascinate", value: "'Fascinate', cursive" },
    { name: "Fascinate Inline", value: "'Fascinate Inline', cursive" },
    { name: "Faster One", value: "'Faster One', cursive" },
    { name: "Federant", value: "'Federant', cursive" },
    { name: "Finger Paint", value: "'Finger Paint', cursive" },
    { name: "Flamenco", value: "'Flamenco', cursive" },
    { name: "Flavors", value: "'Flavors', cursive" },
    { name: "Fontdiner Swanky", value: "'Fontdiner Swanky', cursive" },
    { name: "Forum", value: "'Forum', cursive" },
    { name: "Freckle Face", value: "'Freckle Face', cursive" },
    { name: "Fredericka the Great", value: "'Fredericka the Great', cursive" },
    { name: "Fredoka One", value: "'Fredoka One', cursive" },
    { name: "Frijole", value: "'Frijole', cursive" },
    { name: "Fruktur", value: "'Fruktur', cursive" },
    { name: "Fugaz One", value: "'Fugaz One', cursive" },
    { name: "Galada", value: "'Galada', cursive" },
    { name: "Galindo", value: "'Galindo', cursive" },
    { name: "Geostar", value: "'Geostar', cursive" },
    { name: "Geostar Fill", value: "'Geostar Fill', cursive" },
    { name: "Germania One", value: "'Germania One', cursive" },
    { name: "Girassol", value: "'Girassol', cursive" },
    { name: "Glass Antiqua", value: "'Glass Antiqua', cursive" },
    { name: "Goblin One", value: "'Goblin One', cursive" },
    { name: "Goldman", value: "'Goldman', cursive" },
    { name: "Gorditas", value: "'Gorditas', cursive" },
    { name: "Graduate", value: "'Graduate', cursive" },
    { name: "Grandstander", value: "'Grandstander', cursive" },
    { name: "Gravitas One", value: "'Gravitas One', cursive" },
    { name: "Grenze Gotisch", value: "'Grenze Gotisch', cursive" },
    { name: "Griffy", value: "'Griffy', cursive" },
    { name: "Gruppo", value: "'Gruppo', cursive" },
    { name: "Gugi", value: "'Gugi', cursive" },
    { name: "Hanalei", value: "'Hanalei', cursive" },
    { name: "Hanalei Fill", value: "'Hanalei Fill', cursive" },
    { name: "Happy Monkey", value: "'Happy Monkey', cursive" },
    { name: "Henny Penny", value: "'Henny Penny', cursive" },
    { name: "Iceberg", value: "'Iceberg', cursive" },
    { name: "Iceland", value: "'Iceland', cursive" },
    { name: "Irish Grover", value: "'Irish Grover', cursive" },
    {
        name: "Jacques Francois Shadow",
        value: "'Jacques Francois Shadow', display",
    },
    { name: "Jolly Lodger", value: "'Jolly Lodger', cursive" },
    { name: "Jomhuria", value: "'Jomhuria', cursive" },
    { name: "Joti One", value: "'Joti One', cursive" },
    { name: "Katibeh", value: "'Katibeh', cursive" },
    { name: "Kavoon", value: "'Kavoon', cursive" },
    { name: "Keania One", value: "'Keania One', cursive" },
    { name: "Kelly Slab", value: "'Kelly Slab', cursive" },
    { name: "Kenia", value: "'Kenia', cursive" },
    { name: "Kirang Haerang", value: "'Kirang Haerang', cursive" },
    { name: "Knewave", value: "'Knewave', cursive" },
    { name: "Kranky", value: "'Kranky', cursive" },
    { name: "Kufam", value: "'Kufam', cursive" },
    { name: "Kumar One", value: "'Kumar One', cursive" },
    // { name: "Kumar One Outline", value: "'Kumar One Outline', cursive" },
    { name: "Lacquer", value: "'Lacquer', cursive" },
    { name: "Lalezar", value: "'Lalezar', cursive" },
    { name: "Lancelot", value: "'Lancelot', cursive" },
    { name: "Langar", value: "'Langar', cursive" },
    { name: "Lemon", value: "'Lemon', cursive" },
    { name: "Lemonada", value: "'Lemonada', cursive" },
    { name: "Libre Barcode 128", value: "'Libre Barcode 128', cursive" },
    {
        name: "Libre Barcode 128 Text",
        value: "'Libre Barcode 128 Text', display",
    },
    { name: "Libre Barcode 39", value: "'Libre Barcode 39', cursive" },
    {
        name: "Libre Barcode 39 Extended",
        value: "'Libre Barcode 39 Extended', display",
    },
    {
        name: "Libre Barcode 39 Extended Text",
        value: "'Libre Barcode 39 Extended Text', display",
    },
    {
        name: "Libre Barcode 39 Text",
        value: "'Libre Barcode 39 Text', cursive",
    },
    {
        name: "Libre Barcode EAN13 Text",
        value: "'Libre Barcode EAN13 Text', display",
    },
    { name: "Life Savers", value: "'Life Savers', cursive" },
    { name: "Lilita One", value: "'Lilita One', cursive" },
    { name: "Lily Script One", value: "'Lily Script One', cursive" },
    { name: "Limelight", value: "'Limelight', cursive" },
    { name: "Lobster", value: "'Lobster', cursive" },
    { name: "Lobster Two", value: "'Lobster Two', cursive" },
    { name: "Londrina Outline", value: "'Londrina Outline', cursive" },
    { name: "Londrina Shadow", value: "'Londrina Shadow', cursive" },
    { name: "Londrina Sketch", value: "'Londrina Sketch', cursive" },
    { name: "Londrina Solid", value: "'Londrina Solid', cursive" },
    // {
    //     name: "Love Ya Like A Sister",
    //     value: "'Love Ya Like A Sister', cursive",
    // },
    { name: "Luckiest Guy", value: "'Luckiest Guy', cursive" },
    { name: "Macondo", value: "'Macondo', cursive" },
    { name: "Macondo Swash Caps", value: "'Macondo Swash Caps', cursive" },
    { name: "Maiden Orange", value: "'Maiden Orange', cursive" },
    { name: "Margarine", value: "'Margarine', cursive" },
    { name: "McLaren", value: "'McLaren', cursive" },
    // { name: "MedievalSharp", value: "'MedievalSharp', cursive" },
    { name: "Medula One", value: "'Medula One', cursive" },
    // { name: "Megrim", value: "'Megrim', cursive" },
    { name: "Metal Mania", value: "'Metal Mania', cursive" },
    { name: "Metamorphous", value: "'Metamorphous', cursive" },
    { name: "Milonga", value: "'Milonga', cursive" },
    { name: "Miltonian", value: "'Miltonian', cursive" },
    { name: "Miltonian Tattoo", value: "'Miltonian Tattoo', cursive" },
    { name: "Miniver", value: "'Miniver', cursive" },
    { name: "Mirza", value: "'Mirza', cursive" },
    { name: "Modak", value: "'Modak', cursive" },
    { name: "Modern Antiqua", value: "'Modern Antiqua', cursive" },
    { name: "Mogra", value: "'Mogra', cursive" },
    // { name: "Monofett", value: "'Monofett', cursive" },
    { name: "Monoton", value: "'Monoton', cursive" },
    // {
    //     name: "Mountains of Christmas",
    //     value: "'Mountains of Christmas', display",
    // },
    { name: "MuseoModerno", value: "'MuseoModerno', cursive" },
    { name: "Mystery Quest", value: "'Mystery Quest', cursive" },
    { name: "New Rocker", value: "'New Rocker', cursive" },
    { name: "Nixie One", value: "'Nixie One', cursive" },
    { name: "Nosifer", value: "'Nosifer', cursive" },
    // { name: "Nova Cut", value: "'Nova Cut', cursive" },
    // { name: "Nova Flat", value: "'Nova Flat', cursive" },
    // { name: "Nova Oval", value: "'Nova Oval', cursive" },
    // { name: "Nova Round", value: "'Nova Round', cursive" },
    { name: "Nova Script", value: "'Nova Script', cursive" },
    // { name: "Nova Slim", value: "'Nova Slim', cursive" },
    // { name: "Nova Square", value: "'Nova Square', cursive" },
    { name: "Odibee Sans", value: "'Odibee Sans', cursive" },
    { name: "Offside", value: "'Offside', cursive" },
    { name: "Oi", value: "'Oi', cursive" },
    { name: "Oldenburg", value: "'Oldenburg', cursive" },
    { name: "Oleo Script", value: "'Oleo Script', cursive" },
    {
        name: "Oleo Script Swash Caps",
        value: "'Oleo Script Swash Caps', display",
    },
    { name: "Oregano", value: "'Oregano', cursive" },
    { name: "Original Surfer", value: "'Original Surfer', cursive" },
    { name: "Overlock", value: "'Overlock', cursive" },
    { name: "Overlock SC", value: "'Overlock SC', cursive" },
    { name: "Oxanium", value: "'Oxanium', cursive" },
    { name: "Paprika", value: "'Paprika', cursive" },
    { name: "Passero One", value: "'Passero One', cursive" },
    { name: "Passion One", value: "'Passion One', cursive" },
    { name: "Patua One", value: "'Patua One', cursive" },
    { name: "Peralta", value: "'Peralta', cursive" },
    { name: "Piedra", value: "'Piedra', cursive" },
    { name: "Pirata One", value: "'Pirata One', cursive" },
    { name: "Plaster", value: "'Plaster', cursive" },
    { name: "Playball", value: "'Playball', cursive" },
    { name: "Poiret One", value: "'Poiret One', cursive" },
    // { name: "Poller One", value: "'Poller One', cursive" },
    { name: "Pompiere", value: "'Pompiere', cursive" },
    { name: "Poor Story", value: "'Poor Story', cursive" },
    { name: "Potta One", value: "'Potta One', cursive" },
    { name: "Press Start 2P", value: "'Press Start 2P', cursive" },
    { name: "Prosto One", value: "'Prosto One', cursive" },
    { name: "Purple Purse", value: "'Purple Purse', cursive" },
    { name: "Racing Sans One", value: "'Racing Sans One', cursive" },
    { name: "Rakkas", value: "'Rakkas', cursive" },
    { name: "Raleway Dots", value: "'Raleway Dots', cursive" },
    { name: "Rammetto One", value: "'Rammetto One', cursive" },
    { name: "Ranchers", value: "'Ranchers', cursive" },
    { name: "Ranga", value: "'Ranga', cursive" },
    { name: "Ravi Prakash", value: "'Ravi Prakash', cursive" },
    { name: "Red Rose", value: "'Red Rose', cursive" },
    { name: "Reggae One", value: "'Reggae One', cursive" },
    { name: "Revalia", value: "'Revalia', cursive" },
    { name: "Ribeye", value: "'Ribeye', cursive" },
    { name: "Ribeye Marrow", value: "'Ribeye Marrow', cursive" },
    { name: "Righteous", value: "'Righteous', cursive" },
    { name: "Risque", value: "'Risque', cursive" },
    { name: "Rowdies", value: "'Rowdies', cursive" },
    // { name: "Ruslan Display", value: "'Ruslan Display', cursive" },
    { name: "Rye", value: "'Rye', cursive" },
    { name: "Sail", value: "'Sail', cursive" },
    { name: "Saira Stencil One", value: "'Saira Stencil One', cursive" },
    { name: "Salsa", value: "'Salsa', cursive" },
    { name: "Sancreek", value: "'Sancreek', cursive" },
    { name: "Sansita Swashed", value: "'Sansita Swashed', cursive" },
    { name: "Sarina", value: "'Sarina', cursive" },
    { name: "Seaweed Script", value: "'Seaweed Script', cursive" },
    { name: "Sevillana", value: "'Sevillana', cursive" },
    { name: "Share", value: "'Share', cursive" },
    { name: "Shojumaru", value: "'Shojumaru', cursive" },
    { name: "Shrikhand", value: "'Shrikhand', cursive" },
    { name: "Sigmar One", value: "'Sigmar One', cursive" },
    { name: "Simonetta", value: "'Simonetta', cursive" },
    { name: "Sirin Stencil", value: "'Sirin Stencil', cursive" },
    { name: "Skranji", value: "'Skranji', cursive" },
    { name: "Slackey", value: "'Slackey', cursive" },
    { name: "Smokum", value: "'Smokum', cursive" },
    { name: "Smythe", value: "'Smythe', cursive" },
    { name: "Sniglet", value: "'Sniglet', cursive" },
    { name: "Snowburst One", value: "'Snowburst One', cursive" },
    { name: "Sofadi One", value: "'Sofadi One', cursive" },
    { name: "Sonsie One", value: "'Sonsie One', cursive" },
    { name: "Special Elite", value: "'Special Elite', cursive" },
    { name: "Spicy Rice", value: "'Spicy Rice', cursive" },
    { name: "Spirax", value: "'Spirax', cursive" },
    { name: "Squada One", value: "'Squada One', cursive" },
    { name: "Srisakdi", value: "'Srisakdi', cursive" },
    { name: "Staatliches", value: "'Staatliches', cursive" },
    { name: "Stalinist One", value: "'Stalinist One', cursive" },
    { name: "Stardos Stencil", value: "'Stardos Stencil', cursive" },
    {
        name: "Stint Ultra Condensed",
        value: "'Stint Ultra Condensed', cursive",
    },
    { name: "Stint Ultra Expanded", value: "'Stint Ultra Expanded', cursive" },
    { name: "Supermercado One", value: "'Supermercado One', cursive" },
    { name: "Syne Tactile", value: "'Syne Tactile', cursive" },
    { name: "Titan One", value: "'Titan One', cursive" },
    { name: "Trade Winds", value: "'Trade Winds', cursive" },
    { name: "Trochut", value: "'Trochut', cursive" },
    { name: "Tulpen One", value: "'Tulpen One', cursive" },
    { name: "Turret Road", value: "'Turret Road', cursive" },
    { name: "Uncial Antiqua", value: "'Uncial Antiqua', cursive" },
    { name: "Underdog", value: "'Underdog', cursive" },
    { name: "Unica One", value: "'Unica One', cursive" },
    // { name: "UnifrakturCook", value: "'UnifrakturCook', cursive" },
    // { name: "UnifrakturMaguntia", value: "'UnifrakturMaguntia', cursive" },
    { name: "Unkempt", value: "'Unkempt', cursive" },
    { name: "Unlock", value: "'Unlock', cursive" },
    { name: "Vampiro One", value: "'Vampiro One', cursive" },
    { name: "Vast Shadow", value: "'Vast Shadow', cursive" },
    { name: "Viaoda Libre", value: "'Viaoda Libre', cursive" },
    { name: "Vibes", value: "'Vibes', cursive" },
    { name: "Voces", value: "'Voces', cursive" },
    { name: "Wallpoet", value: "'Wallpoet', cursive" },
    { name: "Warnes", value: "'Warnes', cursive" },
    { name: "Wellfleet", value: "'Wellfleet', cursive" },
    { name: "Yatra One", value: "'Yatra One', cursive" },
    { name: "Yeon Sung", value: "'Yeon Sung', cursive" },
    { name: "Yeseva One", value: "'Yeseva One', cursive" },
    { name: "ZCOOL KuaiLe", value: "'ZCOOL KuaiLe', cursive" },
    {
        name: "ZCOOL QingKe HuangYou",
        value: "'ZCOOL QingKe HuangYou', cursive",
    },
    { name: "Zilla Slab Highlight", value: "'Zilla Slab Highlight', cursive" },
];

export const handwriting = [
    { name: "Aguafina Script", value: "'Aguafina Script', cursive" },
    { name: "Aladin", value: "'Aladin', cursive" },
    { name: "Alex Brush", value: "'Alex Brush', cursive" },
    { name: "Allura", value: "'Allura', cursive" },
    { name: "Amatic SC", value: "'Amatic SC', cursive" },
    { name: "Amita", value: "'Amita', cursive" },
    {
        name: "Annie Use Your Telescope",
        value: "'Annie Use Your Telescope', cursive",
    },
    { name: "Architects Daughter", value: "'Architects Daughter', cursive" },
    { name: "Arizonia", value: "'Arizonia', cursive" },
    { name: "Bad Script", value: "'Bad Script', cursive" },
    { name: "Ballet", value: "'Ballet', cursive" },
    { name: "Berkshire Swash", value: "'Berkshire Swash', cursive" },
    { name: "Beth Ellen", value: "'Beth Ellen', cursive" },
    { name: "Bilbo", value: "'Bilbo', cursive" },
    { name: "Bilbo Swash Caps", value: "'Bilbo Swash Caps', cursive" },
    { name: "Bonbon", value: "'Bonbon', cursive" },
    { name: "Butterfly Kids", value: "'Butterfly Kids', cursive" },
    { name: "Calligraffitti", value: "'Calligraffitti', cursive" },
    { name: "Caveat", value: "'Caveat', cursive" },
    { name: "Caveat Brush", value: "'Caveat Brush', cursive" },
    // { name: "Cedarville Cursive", value: "'Cedarville Cursive', cursive" },
    { name: "Charm", value: "'Charm', cursive" },
    { name: "Charmonman", value: "'Charmonman', cursive" },
    { name: "Chilanka", value: "'Chilanka', cursive" },
    { name: "Clicker Script", value: "'Clicker Script', cursive" },
    { name: "Comic Neue", value: "'Comic Neue', cursive" },
    { name: "Coming Soon", value: "'Coming Soon', cursive" },
    { name: "Condiment", value: "'Condiment', cursive" },
    { name: "Cookie", value: "'Cookie', cursive" },
    { name: "Courgette", value: "'Courgette', cursive" },
    // {
    //     name: "Covered By Your Grace",
    //     value: "'Covered By Your Grace', cursive",
    // },
    { name: "Crafty Girls", value: "'Crafty Girls', cursive" },
    { name: "Damion", value: "'Damion', cursive" },
    { name: "Dancing Script", value: "'Dancing Script', cursive" },
    // { name: "Dawning of a New Day", value: "'Dawning of a New Day', cursive" },
    { name: "Dekko", value: "'Dekko', cursive" },
    { name: "Delius", value: "'Delius', cursive" },
    { name: "Delius Swash Caps", value: "'Delius Swash Caps', cursive" },
    { name: "Delius Unicase", value: "'Delius Unicase', cursive" },
    { name: "Devonshire", value: "'Devonshire', cursive" },
    { name: "Dokdo", value: "'Dokdo', cursive" },
    { name: "Dr Sugiyama", value: "'Dr Sugiyama', cursive" },
    { name: "Eagle Lake", value: "'Eagle Lake', cursive" },
    { name: "East Sea Dokdo", value: "'East Sea Dokdo', cursive" },
    { name: "Engagement", value: "'Engagement', cursive" },
    { name: "Euphoria Script", value: "'Euphoria Script', cursive" },
    { name: "Felipa", value: "'Felipa', cursive" },
    { name: "Fondamento", value: "'Fondamento', cursive" },
    { name: "Gaegu", value: "'Gaegu', cursive" },
    { name: "Gamja Flower", value: "'Gamja Flower', cursive" },
    // { name: "Give You Glory", value: "'Give You Glory', cursive" },
    // { name: "Gloria Hallelujah", value: "'Gloria Hallelujah', cursive" },
    { name: "Gochi Hand", value: "'Gochi Hand', cursive" },
    { name: "Grand Hotel", value: "'Grand Hotel', cursive" },
    // { name: "Great Vibes", value: "'Great Vibes', cursive" },
    { name: "Hachi Maru Pop", value: "'Hachi Maru Pop', cursive" },
    { name: "Handlee", value: "'Handlee', cursive" },
    { name: "Herr Von Muellerhoff", value: "'Herr Von Muellerhoff', cursive" },
    { name: "Hi Melody", value: "'Hi Melody', cursive" },
    { name: "Homemade Apple", value: "'Homemade Apple', cursive" },
    { name: "Indie Flower", value: "'Indie Flower', cursive" },
    { name: "Italianno", value: "'Italianno', cursive" },
    { name: "Itim", value: "'Itim', cursive" },
    { name: "Jim Nightshade", value: "'Jim Nightshade', cursive" },
    { name: "Julee", value: "'Julee', cursive" },
    { name: "Just Another Hand", value: "'Just Another Hand', cursive" },
    // {
    //     name: "Just Me Again Down Here",
    //     value: "'Just Me Again Down Here', cursive",
    // },
    { name: "Kalam", value: "'Kalam', cursive" },
    { name: "Kaushan Script", value: "'Kaushan Script', cursive" },
    { name: "Kavivanar", value: "'Kavivanar', cursive" },
    { name: "Kristi", value: "'Kristi', cursive" },
    // { name: "La Belle Aurore", value: "'La Belle Aurore', cursive" },
    { name: "Lakki Reddy", value: "'Lakki Reddy', cursive" },
    // { name: "Lateef", value: "'Lateef', cursive" },
    { name: "League Script", value: "'League Script', cursive" },
    { name: "Leckerli One", value: "'Leckerli One', cursive" },
    { name: "Liu Jian Mao Cao", value: "'Liu Jian Mao Cao', cursive" },
    { name: "Long Cang", value: "'Long Cang', cursive" },
    // { name: "Loved by the King", value: "'Loved by the King', cursive" },
    { name: "Lovers Quarrel", value: "'Lovers Quarrel', cursive" },
    { name: "Ma Shan Zheng", value: "'Ma Shan Zheng', cursive" },
    { name: "Mali", value: "'Mali', cursive" },
    { name: "Mansalva", value: "'Mansalva', cursive" },
    { name: "Marck Script", value: "'Marck Script', cursive" },
    // { name: "Meddon", value: "'Meddon', cursive" },
    { name: "Meie Script", value: "'Meie Script', cursive" },
    { name: "Merienda", value: "'Merienda', cursive" },
    { name: "Merienda One", value: "'Merienda One', cursive" },
    { name: "Miss Fajardose", value: "'Miss Fajardose', cursive" },
    { name: "Molle", value: "'Molle', cursive" },
    { name: "Monsieur La Doulaise", value: "'Monsieur La Doulaise', cursive" },
    { name: "Montez", value: "'Montez', cursive" },
    { name: "Mr Bedfort", value: "'Mr Bedfort', cursive" },
    { name: "Mr Dafoe", value: "'Mr Dafoe', cursive" },
    { name: "Mr De Haviland", value: "'Mr De Haviland', cursive" },
    { name: "Mrs Saint Delafield", value: "'Mrs Saint Delafield', cursive" },
    { name: "Mrs Sheppards", value: "'Mrs Sheppards', cursive" },
    { name: "Nanum Brush Script", value: "'Nanum Brush Script', cursive" },
    { name: "Nanum Pen Script", value: "'Nanum Pen Script', cursive" },
    { name: "Nerko One", value: "'Nerko One', cursive" },
    // { name: "Neucha", value: "'Neucha', cursive" },
    { name: "Niconne", value: "'Niconne', cursive" },
    { name: "Norican", value: "'Norican', cursive" },
    // { name: "Nothing You Could Do", value: "'Nothing You Could Do', cursive" },
    // { name: "Over the Rainbow", value: "'Over the Rainbow', cursive" },
    { name: "Pacifico", value: "'Pacifico', cursive" },
    { name: "Pangolin", value: "'Pangolin', cursive" },
    { name: "Parisienne", value: "'Parisienne', cursive" },
    { name: "Patrick Hand", value: "'Patrick Hand', cursive" },
    { name: "Patrick Hand SC", value: "'Patrick Hand SC', cursive" },
    { name: "Permanent Marker", value: "'Permanent Marker', cursive" },
    { name: "Petit Formal Script", value: "'Petit Formal Script', cursive" },
    { name: "Pinyon Script", value: "'Pinyon Script', cursive" },
    { name: "Princess Sofia", value: "'Princess Sofia', cursive" },
    { name: "Quintessential", value: "'Quintessential', cursive" },
    { name: "Qwigley", value: "'Qwigley', cursive" },
    { name: "Rancho", value: "'Rancho', cursive" },
    { name: "Redressed", value: "'Redressed', cursive" },
    // { name: "Reenie Beanie", value: "'Reenie Beanie', cursive" },
    { name: "Rochester", value: "'Rochester', cursive" },
    { name: "Rock Salt", value: "'Rock Salt', cursive" },
    { name: "Romanesco", value: "'Romanesco', cursive" },
    { name: "Rouge Script", value: "'Rouge Script', cursive" },
    { name: "Ruge Boogie", value: "'Ruge Boogie', cursive" },
    { name: "Ruthie", value: "'Ruthie', cursive" },
    { name: "Sacramento", value: "'Sacramento', cursive" },
    { name: "Satisfy", value: "'Satisfy', cursive" },
    { name: "Schoolbell", value: "'Schoolbell', cursive" },
    { name: "Sedgwick Ave", value: "'Sedgwick Ave', cursive" },
    { name: "Sedgwick Ave Display", value: "'Sedgwick Ave Display', cursive" },
    // { name: "Shadows Into Light", value: "'Shadows Into Light', cursive" },
    {
        name: "Shadows Into Light Two",
        value: "'Shadows Into Light Two', cursive",
    },
    { name: "Short Stack", value: "'Short Stack', cursive" },
    { name: "Sofia", value: "'Sofia', cursive" },
    { name: "Sriracha", value: "'Sriracha', cursive" },
    { name: "Stalemate", value: "'Stalemate', cursive" },
    { name: "Sue Ellen Francisco", value: "'Sue Ellen Francisco', cursive" },
    { name: "Sunshiney", value: "'Sunshiney', cursive" },
    // { name: "Swanky and Moo Moo", value: "'Swanky and Moo Moo', cursive" },
    { name: "Tangerine", value: "'Tangerine', cursive" },
    // { name: "The Girl Next Door", value: "'The Girl Next Door', cursive" },
    { name: "Tillana", value: "'Tillana', cursive" },
    { name: "Vibur", value: "'Vibur', cursive" },
    // {
    //     name: "Waiting for the Sunrise",
    //     value: "'Waiting for the Sunrise', cursive",
    // },
    { name: "Walter Turncoat", value: "'Walter Turncoat', cursive" },
    { name: "Yellowtail", value: "'Yellowtail', cursive" },
    { name: "Yesteryear", value: "'Yesteryear', cursive" },
    // { name: "Zeyada", value: "'Zeyada', cursive" },
    { name: "Zhi Mang Xing", value: "'Zhi Mang Xing', cursive" },
];

export const monospace = [
    { name: "Anonymous Pro", value: "'Anonymous Pro', monospace" },
    { name: "B612 Mono", value: "'B612 Mono', monospace" },
    { name: "Courier Prime", value: "'Courier Prime', monospace" },
    { name: "Cousine", value: "'Cousine', monospace" },
    { name: "Cutive Mono", value: "'Cutive Mono', monospace" },
    { name: "DM Mono", value: "'DM Mono', monospace" },
    { name: "Fira Code", value: "'Fira Code', monospace" },
    { name: "Fira Mono", value: "'Fira Mono', monospace" },
    { name: "IBM Plex Mono", value: "'IBM Plex Mono', monospace" },
    { name: "Inconsolata", value: "'Inconsolata', monospace" },
    { name: "JetBrains Mono", value: "'JetBrains Mono', monospace" },
    { name: "Major Mono Display", value: "'Major Mono Display', monospace" },
    { name: "Nanum Gothic Coding", value: "'Nanum Gothic Coding', monospace" },
    // { name: "Nova Mono", value: "'Nova Mono', monospace" },
    { name: "Overpass Mono", value: "'Overpass Mono', monospace" },
    { name: "Oxygen Mono", value: "'Oxygen Mono', monospace" },
    // { name: "PT Mono", value: "'PT Mono', monospace" },
    { name: "Roboto Mono", value: "'Roboto Mono', monospace" },
    { name: "Share Tech Mono", value: "'Share Tech Mono', monospace" },
    { name: "Source Code Pro", value: "'Source Code Pro', monospace" },
    { name: "Space Mono", value: "'Space Mono', monospace" },
    { name: "Syne Mono", value: "'Syne Mono', monospace" },
    // { name: "Ubuntu Mono", value: "'Ubuntu Mono', monospace" },
    { name: "VT323", value: "'VT323', monospace" },
    { name: "Xanh Mono", value: "'Xanh Mono', monospace" },
];

export const sansSerif = [
    {
        name: "ABeeZee",
        value: "'ABeeZee', sans-serif",
    },
    {
        name: "Abel",
        value: "'Abel', sans-serif",
    },
    {
        name: "Aclonica",
        value: "'Aclonica', sans-serif",
    },
    {
        name: "Acme",
        value: "'Acme', sans-serif",
    },
    {
        name: "Actor",
        value: "'Actor', sans-serif",
    },
    {
        name: "Advent Pro",
        value: "'Advent Pro', sans-serif",
    },
    {
        name: "Alata",
        value: "'Alata', sans-serif",
    },
    {
        name: "Alatsi",
        value: "'Alatsi', sans-serif",
    },
    {
        name: "Aldrich",
        value: "'Aldrich', sans-serif",
    },
    {
        name: "Alef",
        value: "'Alef', sans-serif",
    },
    {
        name: "Alegreya Sans",
        value: "'Alegreya Sans', sans-serif",
    },
    {
        name: "Alegreya Sans SC",
        value: "'Alegreya Sans SC', sans-serif",
    },
    {
        name: "Allerta",
        value: "'Allerta', sans-serif",
    },
    {
        name: "Allerta Stencil",
        value: "'Allerta Stencil', sans-serif",
    },
    {
        name: "Amaranth",
        value: "'Amaranth', sans-serif",
    },
    {
        name: "Amiko",
        value: "'Amiko', sans-serif",
    },
    {
        name: "Anaheim",
        value: "'Anaheim', sans-serif",
    },
    {
        name: "Andika",
        value: "'Andika', sans-serif",
    },
    {
        name: "Andika New Basic",
        value: "'Andika New Basic', sans-serif",
    },
    {
        name: "Antic",
        value: "'Antic', sans-serif",
    },
    {
        name: "Anton",
        value: "'Anton', sans-serif",
    },
    // {
    //     name: "Archivo",
    //     value: "'Archivo', sans-serif",
    // },
    {
        name: "Archivo Black",
        value: "'Archivo Black', sans-serif",
    },
    {
        name: "Archivo Narrow",
        value: "'Archivo Narrow', sans-serif",
    },
    {
        name: "Arimo",
        value: "'Arimo', sans-serif",
    },
    {
        name: "Armata",
        value: "'Armata', sans-serif",
    },
    {
        name: "Arsenal",
        value: "'Arsenal', sans-serif",
    },
    {
        name: "Arya",
        value: "'Arya', sans-serif",
    },
    {
        name: "Asap",
        value: "'Asap', sans-serif",
    },
    {
        name: "Asap Condensed",
        value: "'Asap Condensed', sans-serif",
    },
    {
        name: "Assistant",
        value: "'Assistant', sans-serif",
    },
    {
        name: "Asul",
        value: "'Asul', sans-serif",
    },
    {
        name: "Athiti",
        value: "'Athiti', sans-serif",
    },
    {
        name: "Average Sans",
        value: "'Average Sans', sans-serif",
    },
    {
        name: "B612",
        value: "'B612', sans-serif",
    },
    {
        name: "Bai Jamjuree",
        value: "'Bai Jamjuree', sans-serif",
    },
    {
        name: "Barlow",
        value: "'Barlow', sans-serif",
    },
    {
        name: "Barlow Condensed",
        value: "'Barlow Condensed', sans-serif",
    },
    {
        name: "Barlow Semi Condensed",
        value: "'Barlow Semi Condensed', sans-serif",
    },
    {
        name: "Basic",
        value: "'Basic', sans-serif",
    },
    {
        name: "Be Vietnam",
        value: "'Be Vietnam', sans-serif",
    },
    {
        name: "Belleza",
        value: "'Belleza', sans-serif",
    },
    {
        name: "BenchNine",
        value: "'BenchNine', sans-serif",
    },
    {
        name: "Biryani",
        value: "'Biryani', sans-serif",
    },
    {
        name: "Black And White Picture",
        value: "'Black And White Picture', sans-serif",
    },
    {
        name: "Black Han Sans",
        value: "'Black Han Sans', sans-serif",
    },
    {
        name: "Blinker",
        value: "'Blinker', sans-serif",
    },
    {
        name: "Bubbler One",
        value: "'Bubbler One', sans-serif",
    },
    {
        name: "Cabin",
        value: "'Cabin', sans-serif",
    },
    {
        name: "Cabin Condensed",
        value: "'Cabin Condensed', sans-serif",
    },
    {
        name: "Cagliostro",
        value: "'Cagliostro', sans-serif",
    },
    {
        name: "Cairo",
        value: "'Cairo', sans-serif",
    },
    {
        name: "Cambay",
        value: "'Cambay', sans-serif",
    },
    // {
    //     name: "Candal",
    //     value: "'Candal', sans-serif",
    // },
    {
        name: "Cantarell",
        value: "'Cantarell', sans-serif",
    },
    {
        name: "Cantora One",
        value: "'Cantora One', sans-serif",
    },
    {
        name: "Capriola",
        value: "'Capriola', sans-serif",
    },
    {
        name: "Carme",
        value: "'Carme', sans-serif",
    },
    {
        name: "Carrois Gothic",
        value: "'Carrois Gothic', sans-serif",
    },
    {
        name: "Carrois Gothic SC",
        value: "'Carrois Gothic SC', sans-serif",
    },
    {
        name: "Catamaran",
        value: "'Catamaran', sans-serif",
    },
    {
        name: "Chakra Petch",
        value: "'Chakra Petch', sans-serif",
    },
    {
        name: "Changa",
        value: "'Changa', sans-serif",
    },
    {
        name: "Chathura",
        value: "'Chathura', sans-serif",
    },
    {
        name: "Chau Philomene One",
        value: "'Chau Philomene One', sans-serif",
    },
    {
        name: "Chivo",
        value: "'Chivo', sans-serif",
    },
    // {
    //     name: "Coda Caption",
    //     value: "'Coda Caption', sans-serif",
    // },
    {
        name: "Commissioner",
        value: "'Commissioner', sans-serif",
    },
    {
        name: "Convergence",
        value: "'Convergence', sans-serif",
    },
    {
        name: "Cuprum",
        value: "'Cuprum', sans-serif",
    },
    {
        name: "Darker Grotesque",
        value: "'Darker Grotesque', sans-serif",
    },
    {
        name: "Days One",
        value: "'Days One', sans-serif",
    },
    {
        name: "Denk One",
        value: "'Denk One', sans-serif",
    },
    {
        name: "Dhurjati",
        value: "'Dhurjati', sans-serif",
    },
    {
        name: "Didact Gothic",
        value: "'Didact Gothic', sans-serif",
    },
    {
        name: "DM Sans",
        value: "'DM Sans', sans-serif",
    },
    {
        name: "Do Hyeon",
        value: "'Do Hyeon', sans-serif",
    },
    {
        name: "Doppio One",
        value: "'Doppio One', sans-serif",
    },
    {
        name: "Dorsa",
        value: "'Dorsa', sans-serif",
    },
    {
        name: "Dosis",
        value: "'Dosis', sans-serif",
    },
    {
        name: "DotGothic16",
        value: "'DotGothic16', sans-serif",
    },
    {
        name: "Duru Sans",
        value: "'Duru Sans', sans-serif",
    },
    {
        name: "Economica",
        value: "'Economica', sans-serif",
    },
    {
        name: "El Messiri",
        value: "'El Messiri', sans-serif",
    },
    {
        name: "Electrolize",
        value: "'Electrolize', sans-serif",
    },
    {
        name: "Encode Sans",
        value: "'Encode Sans', sans-serif",
    },
    {
        name: "Encode Sans Condensed",
        value: "'Encode Sans Condensed', sans-serif",
    },
    {
        name: "Encode Sans Expanded",
        value: "'Encode Sans Expanded', sans-serif",
    },
    {
        name: "Encode Sans Semi Condensed",
        value: "'Encode Sans Semi Condensed', sans-serif",
    },
    {
        name: "Encode Sans Semi Expanded",
        value: "'Encode Sans Semi Expanded', sans-serif",
    },
    {
        name: "Englebert",
        value: "'Englebert', sans-serif",
    },
    {
        name: "Epilogue",
        value: "'Epilogue', sans-serif",
    },
    {
        name: "Exo",
        value: "'Exo', sans-serif",
    },
    {
        name: "Exo 2",
        value: "'Exo 2', sans-serif",
    },
    {
        name: "Fahkwang",
        value: "'Fahkwang', sans-serif",
    },
    {
        name: "Farro",
        value: "'Farro', sans-serif",
    },
    {
        name: "Federo",
        value: "'Federo', sans-serif",
    },
    {
        name: "Fira Sans",
        value: "'Fira Sans', sans-serif",
    },
    {
        name: "Fira Sans Condensed",
        value: "'Fira Sans Condensed', sans-serif",
    },
    {
        name: "Fira Sans Extra Condensed",
        value: "'Fira Sans Extra Condensed', sans-serif",
    },
    {
        name: "Fjalla One",
        value: "'Fjalla One', sans-serif",
    },
    {
        name: "Francois One",
        value: "'Francois One', sans-serif",
    },
    {
        name: "Fresca",
        value: "'Fresca', sans-serif",
    },
    {
        name: "Gafata",
        value: "'Gafata', sans-serif",
    },
    {
        name: "Galdeano",
        value: "'Galdeano', sans-serif",
    },
    {
        name: "Gayathri",
        value: "'Gayathri', sans-serif",
    },
    {
        name: "Geo",
        value: "'Geo', sans-serif",
    },
    {
        name: "Gidugu",
        value: "'Gidugu', sans-serif",
    },
    {
        name: "Gothic A1",
        value: "'Gothic A1', sans-serif",
    },
    {
        name: "Gotu",
        value: "'Gotu', sans-serif",
    },
    {
        name: "Gudea",
        value: "'Gudea', sans-serif",
    },
    {
        name: "Hammersmith One",
        value: "'Hammersmith One', sans-serif",
    },
    {
        name: "Harmattan",
        value: "'Harmattan', sans-serif",
    },
    {
        name: "Heebo",
        value: "'Heebo', sans-serif",
    },
    {
        name: "Hind",
        value: "'Hind', sans-serif",
    },
    {
        name: "Hind Guntur",
        value: "'Hind Guntur', sans-serif",
    },
    {
        name: "Hind Madurai",
        value: "'Hind Madurai', sans-serif",
    },
    {
        name: "Hind Siliguri",
        value: "'Hind Siliguri', sans-serif",
    },
    {
        name: "Hind Vadodara",
        value: "'Hind Vadodara', sans-serif",
    },
    {
        name: "Homenaje",
        value: "'Homenaje', sans-serif",
    },
    {
        name: "IBM Plex Sans",
        value: "'IBM Plex Sans', sans-serif",
    },
    {
        name: "IBM Plex Sans Condensed",
        value: "'IBM Plex Sans Condensed', sans-serif",
    },
    {
        name: "Imprima",
        value: "'Imprima', sans-serif",
    },
    {
        name: "Inder",
        value: "'Inder', sans-serif",
    },
    {
        name: "Inria Sans",
        value: "'Inria Sans', sans-serif",
    },
    // {
    //     name: "Inter",
    //     value: "'Inter', sans-serif",
    // },
    {
        name: "Istok Web",
        value: "'Istok Web', sans-serif",
    },
    {
        name: "Jaldi",
        value: "'Jaldi', sans-serif",
    },
    {
        name: "Jockey One",
        value: "'Jockey One', sans-serif",
    },
    {
        name: "Josefin Sans",
        value: "'Josefin Sans', sans-serif",
    },
    {
        name: "Jost",
        value: "'Jost', sans-serif",
    },
    {
        name: "Jua",
        value: "'Jua', sans-serif",
    },
    {
        name: "Julius Sans One",
        value: "'Julius Sans One', sans-serif",
    },
    // {
    //     name: "Jura",
    //     value: "'Jura', sans-serif",
    // },
    {
        name: "K2D",
        value: "'K2D', sans-serif",
    },
    {
        name: "Kanit",
        value: "'Kanit', sans-serif",
    },
    {
        name: "Karla",
        value: "'Karla', sans-serif",
    },
    {
        name: "Khand",
        value: "'Khand', sans-serif",
    },
    {
        name: "Khula",
        value: "'Khula', sans-serif",
    },
    {
        name: "Kite One",
        value: "'Kite One', sans-serif",
    },
    {
        name: "Kodchasan",
        value: "'Kodchasan', sans-serif",
    },
    {
        name: "KoHo",
        value: "'KoHo', sans-serif",
    },
    // {
    //     name: "Kosugi",
    //     value: "'Kosugi', sans-serif",
    // },
    // {
    //     name: "Kosugi Maru",
    //     value: "'Kosugi Maru', sans-serif",
    // },
    {
        name: "Krona One",
        value: "'Krona One', sans-serif",
    },
    {
        name: "Krub",
        value: "'Krub', sans-serif",
    },
    {
        name: "Kulim Park",
        value: "'Kulim Park', sans-serif",
    },
    {
        name: "Kumbh Sans",
        value: "'Kumbh Sans', sans-serif",
    },
    {
        name: "Laila",
        value: "'Laila', sans-serif",
    },
    {
        name: "Lato",
        value: "'Lato', sans-serif",
    },
    {
        name: "Lekton",
        value: "'Lekton', sans-serif",
    },
    {
        name: "Lexend Deca",
        value: "'Lexend Deca', sans-serif",
    },
    {
        name: "Lexend Exa",
        value: "'Lexend Exa', sans-serif",
    },
    {
        name: "Lexend Giga",
        value: "'Lexend Giga', sans-serif",
    },
    {
        name: "Lexend Mega",
        value: "'Lexend Mega', sans-serif",
    },
    {
        name: "Lexend Peta",
        value: "'Lexend Peta', sans-serif",
    },
    {
        name: "Lexend Tera",
        value: "'Lexend Tera', sans-serif",
    },
    {
        name: "Lexend Zetta",
        value: "'Lexend Zetta', sans-serif",
    },
    {
        name: "Libre Franklin",
        value: "'Libre Franklin', sans-serif",
    },
    {
        name: "Livvic",
        value: "'Livvic', sans-serif",
    },
    // {
    //     name: "M PLUS 1p",
    //     value: "'M PLUS 1p', sans-serif",
    // },
    // {
    //     name: "M PLUS Rounded 1c",
    //     value: "'M PLUS Rounded 1c', sans-serif",
    // },
    {
        name: "Mada",
        value: "'Mada', sans-serif",
    },
    {
        name: "Magra",
        value: "'Magra', sans-serif",
    },
    {
        name: "Mako",
        value: "'Mako', sans-serif",
    },
    {
        name: "Mallanna",
        value: "'Mallanna', sans-serif",
    },
    {
        name: "Mandali",
        value: "'Mandali', sans-serif",
    },
    {
        name: "Manjari",
        value: "'Manjari', sans-serif",
    },
    {
        name: "Manrope",
        value: "'Manrope', sans-serif",
    },
    {
        name: "Marmelad",
        value: "'Marmelad', sans-serif",
    },
    {
        name: "Martel Sans",
        value: "'Martel Sans', sans-serif",
    },
    {
        name: "Marvel",
        value: "'Marvel', sans-serif",
    },
    {
        name: "Maven Pro",
        value: "'Maven Pro', sans-serif",
    },
    {
        name: "Meera Inimai",
        value: "'Meera Inimai', sans-serif",
    },
    {
        name: "Merriweather Sans",
        value: "'Merriweather Sans', sans-serif",
    },
    {
        name: "Metrophobic",
        value: "'Metrophobic', sans-serif",
    },
    // {
    //     name: "Michroma",
    //     value: "'Michroma', sans-serif",
    // },
    {
        name: "Mina",
        value: "'Mina', sans-serif",
    },
    {
        name: "Miriam Libre",
        value: "'Miriam Libre', sans-serif",
    },
    {
        name: "Mitr",
        value: "'Mitr', sans-serif",
    },
    {
        name: "Molengo",
        value: "'Molengo', sans-serif",
    },
    {
        name: "Monda",
        value: "'Monda', sans-serif",
    },
    {
        name: "Montserrat",
        value: "'Montserrat', sans-serif",
    },
    {
        name: "Montserrat Alternates",
        value: "'Montserrat Alternates', sans-serif",
    },
    {
        name: "Montserrat Subrayada",
        value: "'Montserrat Subrayada', sans-serif",
    },
    {
        name: "Mouse Memoirs",
        value: "'Mouse Memoirs', sans-serif",
    },
    {
        name: "Mukta",
        value: "'Mukta', sans-serif",
    },
    {
        name: "Mukta Mahee",
        value: "'Mukta Mahee', sans-serif",
    },
    {
        name: "Mukta Malar",
        value: "'Mukta Malar', sans-serif",
    },
    {
        name: "Mukta Vaani",
        value: "'Mukta Vaani', sans-serif",
    },
    {
        name: "Mulish",
        value: "'Mulish', sans-serif",
    },
    {
        name: "Nanum Gothic",
        value: "'Nanum Gothic', sans-serif",
    },
    {
        name: "News Cycle",
        value: "'News Cycle', sans-serif",
    },
    {
        name: "Niramit",
        value: "'Niramit', sans-serif",
    },
    {
        name: "Nobile",
        value: "'Nobile', sans-serif",
    },
    {
        name: "Notable",
        value: "'Notable', sans-serif",
    },
    {
        name: "Noto Sans",
        value: "'Noto Sans', sans-serif",
    },
    // {
    //     name: "Noto Sans HK",
    //     value: "'Noto Sans HK', sans-serif",
    // },
    // {
    //     name: "Noto Sans JP",
    //     value: "'Noto Sans JP', sans-serif",
    // },
    // {
    //     name: "Noto Sans KR",
    //     value: "'Noto Sans KR', sans-serif",
    // },
    // {
    //     name: "Noto Sans SC",
    //     value: "'Noto Sans SC', sans-serif",
    // },
    // {
    //     name: "Noto Sans TC",
    //     value: "'Noto Sans TC', sans-serif",
    // },
    {
        name: "NTR",
        value: "'NTR', sans-serif",
    },
    {
        name: "Numans",
        value: "'Numans', sans-serif",
    },
    {
        name: "Nunito",
        value: "'Nunito', sans-serif",
    },
    {
        name: "Nunito Sans",
        value: "'Nunito Sans', sans-serif",
    },
    // {
    //     name: "Open Sans",
    //     value: "'Open Sans', sans-serif",
    // },
    // {
    //     name: "Open Sans Condensed",
    //     value: "'Open Sans Condensed', sans-serif",
    // },
    {
        name: "Orbitron",
        value: "'Orbitron', sans-serif",
    },
    {
        name: "Orienta",
        value: "'Orienta', sans-serif",
    },
    {
        name: "Oswald",
        value: "'Oswald', sans-serif",
    },
    {
        name: "Overpass",
        value: "'Overpass', sans-serif",
    },
    {
        name: "Oxygen",
        value: "'Oxygen', sans-serif",
    },
    {
        name: "Padauk",
        value: "'Padauk', sans-serif",
    },
    {
        name: "Palanquin",
        value: "'Palanquin', sans-serif",
    },
    {
        name: "Palanquin Dark",
        value: "'Palanquin Dark', sans-serif",
    },
    {
        name: "Pathway Gothic One",
        value: "'Pathway Gothic One', sans-serif",
    },
    {
        name: "Pattaya",
        value: "'Pattaya', sans-serif",
    },
    {
        name: "Pavanam",
        value: "'Pavanam', sans-serif",
    },
    {
        name: "Paytone One",
        value: "'Paytone One', sans-serif",
    },
    {
        name: "Philosopher",
        value: "'Philosopher', sans-serif",
    },
    {
        name: "Play",
        value: "'Play', sans-serif",
    },
    {
        name: "Pontano Sans",
        value: "'Pontano Sans', sans-serif",
    },
    {
        name: "Poppins",
        value: "'Poppins', sans-serif",
    },
    {
        name: "Port Lligat Sans",
        value: "'Port Lligat Sans', sans-serif",
    },
    {
        name: "Pragati Narrow",
        value: "'Pragati Narrow', sans-serif",
    },
    {
        name: "Prompt",
        value: "'Prompt', sans-serif",
    },
    {
        name: "Proza Libre",
        value: "'Proza Libre', sans-serif",
    },
    {
        name: "PT Sans",
        value: "'PT Sans', sans-serif",
    },
    {
        name: "PT Sans Caption",
        value: "'PT Sans Caption', sans-serif",
    },
    {
        name: "PT Sans Narrow",
        value: "'PT Sans Narrow', sans-serif",
    },
    {
        name: "Public Sans",
        value: "'Public Sans', sans-serif",
    },
    {
        name: "Puritan",
        value: "'Puritan', sans-serif",
    },
    {
        name: "Quantico",
        value: "'Quantico', sans-serif",
    },
    {
        name: "Quattrocento Sans",
        value: "'Quattrocento Sans', sans-serif",
    },
    {
        name: "Questrial",
        value: "'Questrial', sans-serif",
    },
    {
        name: "Quicksand",
        value: "'Quicksand', sans-serif",
    },
    {
        name: "Rajdhani",
        value: "'Rajdhani', sans-serif",
    },
    {
        name: "Raleway",
        value: "'Raleway', sans-serif",
    },
    {
        name: "Ramabhadra",
        value: "'Ramabhadra', sans-serif",
    },
    {
        name: "Rambla",
        value: "'Rambla', sans-serif",
    },
    {
        name: "Rationale",
        value: "'Rationale', sans-serif",
    },
    // {
    //     name: "Recursive",
    //     value: "'Recursive', sans-serif",
    // },
    {
        name: "Red Hat Display",
        value: "'Red Hat Display', sans-serif",
    },
    {
        name: "Red Hat Text",
        value: "'Red Hat Text', sans-serif",
    },
    {
        name: "Reem Kufi",
        value: "'Reem Kufi', sans-serif",
    },
    {
        name: "Roboto",
        value: "'Roboto', sans-serif",
    },
    {
        name: "Roboto Condensed",
        value: "'Roboto Condensed', sans-serif",
    },
    {
        name: "RocknRoll One",
        value: "'RocknRoll One', sans-serif",
    },
    {
        name: "Ropa Sans",
        value: "'Ropa Sans', sans-serif",
    },
    {
        name: "Rosario",
        value: "'Rosario', sans-serif",
    },
    {
        name: "Rubik",
        value: "'Rubik', sans-serif",
    },
    {
        name: "Rubik Mono One",
        value: "'Rubik Mono One', sans-serif",
    },
    {
        name: "Ruda",
        value: "'Ruda', sans-serif",
    },
    {
        name: "Ruluko",
        value: "'Ruluko', sans-serif",
    },
    {
        name: "Rum Raisin",
        value: "'Rum Raisin', sans-serif",
    },
    {
        name: "Russo One",
        value: "'Russo One', sans-serif",
    },
    {
        name: "Saira",
        value: "'Saira', sans-serif",
    },
    {
        name: "Saira Condensed",
        value: "'Saira Condensed', sans-serif",
    },
    {
        name: "Saira Extra Condensed",
        value: "'Saira Extra Condensed', sans-serif",
    },
    {
        name: "Saira Semi Condensed",
        value: "'Saira Semi Condensed', sans-serif",
    },
    {
        name: "Sansita",
        value: "'Sansita', sans-serif",
    },
    {
        name: "Sarabun",
        value: "'Sarabun', sans-serif",
    },
    {
        name: "Sarala",
        value: "'Sarala', sans-serif",
    },
    {
        name: "Sarpanch",
        value: "'Sarpanch', sans-serif",
    },
    {
        name: "Sawarabi Gothic",
        value: "'Sawarabi Gothic', sans-serif",
    },
    {
        name: "Sawarabi Mincho",
        value: "'Sawarabi Mincho', sans-serif",
    },
    {
        name: "Scada",
        value: "'Scada', sans-serif",
    },
    {
        name: "Secular One",
        value: "'Secular One', sans-serif",
    },
    {
        name: "Sen",
        value: "'Sen', sans-serif",
    },
    {
        name: "Seymour One",
        value: "'Seymour One', sans-serif",
    },
    {
        name: "Shanti",
        value: "'Shanti', sans-serif",
    },
    {
        name: "Share Tech",
        value: "'Share Tech', sans-serif",
    },
    {
        name: "Signika",
        value: "'Signika', sans-serif",
    },
    {
        name: "Signika Negative",
        value: "'Signika Negative', sans-serif",
    },
    {
        name: "Sintony",
        value: "'Sintony', sans-serif",
    },
    // {
    //     name: "Six Caps",
    //     value: "'Six Caps', sans-serif",
    // },
    // {
    //     name: "Snippet",
    //     value: "'Snippet', sans-serif",
    // },
    {
        name: "Sora",
        value: "'Sora', sans-serif",
    },
    {
        name: "Source Sans Pro",
        value: "'Source Sans Pro', sans-serif",
    },
    {
        name: "Space Grotesk",
        value: "'Space Grotesk', sans-serif",
    },
    {
        name: "Spartan",
        value: "'Spartan', sans-serif",
    },
    {
        name: "Spinnaker",
        value: "'Spinnaker', sans-serif",
    },
    {
        name: "Stick",
        value: "'Stick', sans-serif",
    },
    {
        name: "Strait",
        value: "'Strait', sans-serif",
    },
    {
        name: "Stylish",
        value: "'Stylish', sans-serif",
    },
    {
        name: "Sulphur Point",
        value: "'Sulphur Point', sans-serif",
    },
    // {
    //     name: "Sunflower",
    //     value: "'Sunflower', sans-serif",
    // },
    {
        name: "Syncopate",
        value: "'Syncopate', sans-serif",
    },
    // {
    //     name: "Syne",
    //     value: "'Syne', sans-serif",
    // },
    // {
    //     name: "Tajawal",
    //     value: "'Tajawal', sans-serif",
    // },
    {
        name: "Tauri",
        value: "'Tauri', sans-serif",
    },
    {
        name: "Teko",
        value: "'Teko', sans-serif",
    },
    {
        name: "Telex",
        value: "'Telex', sans-serif",
    },
    {
        name: "Tenali Ramakrishna",
        value: "'Tenali Ramakrishna', sans-serif",
    },
    {
        name: "Tenor Sans",
        value: "'Tenor Sans', sans-serif",
    },
    {
        name: "Text Me One",
        value: "'Text Me One', sans-serif",
    },
    {
        name: "Thasadith",
        value: "'Thasadith', sans-serif",
    },
    {
        name: "Timmana",
        value: "'Timmana', sans-serif",
    },
    {
        name: "Titillium Web",
        value: "'Titillium Web', sans-serif",
    },
    {
        name: "Tomorrow",
        value: "'Tomorrow', sans-serif",
    },
    {
        name: "Trispace",
        value: "'Trispace', sans-serif",
    },
    // {
    //     name: "Truculenta",
    //     value: "'Truculenta', sans-serif",
    // },
    // {
    //     name: "Ubuntu",
    //     value: "'Ubuntu', sans-serif",
    // },
    // {
    //     name: "Ubuntu Condensed",
    //     value: "'Ubuntu Condensed', sans-serif",
    // },
    {
        name: "Varela",
        value: "'Varela', sans-serif",
    },
    {
        name: "Varela Round",
        value: "'Varela Round', sans-serif",
    },
    {
        name: "Varta",
        value: "'Varta', sans-serif",
    },
    {
        name: "Viga",
        value: "'Viga', sans-serif",
    },
    {
        name: "Voltaire",
        value: "'Voltaire', sans-serif",
    },
    {
        name: "Wendy One",
        value: "'Wendy One', sans-serif",
    },
    // {
    //     name: "Wire One",
    //     value: "'Wire One', sans-serif",
    // },
    {
        name: "Work Sans",
        value: "'Work Sans', sans-serif",
    },
    {
        name: "Yanone Kaffeesatz",
        value: "'Yanone Kaffeesatz', sans-serif",
    },
    {
        name: "Yantramanav",
        value: "'Yantramanav', sans-serif",
    },
    {
        name: "Yusei Magic",
        value: "'Yusei Magic', sans-serif",
    },
];

export const serif = [
    { name: "Abhaya Libre", value: "'Abhaya Libre', serif" },
    { name: "Adamina", value: "'Adamina', serif" },
    // { name: "Alegreya", value: "'Alegreya', serif" },
    { name: "Alegreya SC", value: "'Alegreya SC', serif" },
    { name: "Aleo", value: "'Aleo', serif" },
    { name: "Alice", value: "'Alice', serif" },
    { name: "Alike", value: "'Alike', serif" },
    { name: "Alike Angular", value: "'Alike Angular', serif" },
    { name: "Almendra", value: "'Almendra', serif" },
    { name: "Almendra SC", value: "'Almendra SC', serif" },
    { name: "Amethysta", value: "'Amethysta', serif" },
    { name: "Amiri", value: "'Amiri', serif" },
    { name: "Andada", value: "'Andada', serif" },
    { name: "Antic Didone", value: "'Antic Didone', serif" },
    { name: "Antic Slab", value: "'Antic Slab', serif" },
    { name: "Arapey", value: "'Arapey', serif" },
    { name: "Arbutus Slab", value: "'Arbutus Slab', serif" },
    { name: "Aref Ruqaa", value: "'Aref Ruqaa', serif" },
    { name: "Artifika", value: "'Artifika', serif" },
    { name: "Arvo", value: "'Arvo', serif" },
    { name: "Asar", value: "'Asar', serif" },
    { name: "Average", value: "'Average', serif" },
    { name: "Balthazar", value: "'Balthazar', serif" },
    { name: "Baskervville", value: "'Baskervville', serif" },
    { name: "Belgrano", value: "'Belgrano', serif" },
    { name: "Bellefair", value: "'Bellefair', serif" },
    { name: "Benne", value: "'Benne', serif" },
    // { name: "Benthem", value: "'Benthem', serif" },
    { name: "BioRhyme", value: "'BioRhyme', serif" },
    { name: "BioRhyme Expanded", value: "'BioRhyme Expanded', serif" },
    { name: "Bitter", value: "'Bitter', serif" },
    // { name: "Bodoni Moda", value: "'Bodoni Moda', serif" },
    { name: "Brawler", value: "'Brawler', serif" },
    { name: "Bree Serif", value: "'Bree Serif', serif" },
    // { name: "Brygada 1918", value: "'Brygada 1918', serif" },
    { name: "Buenard", value: "'Buenard', serif" },
    { name: "Caladea", value: "'Caladea', serif" },
    { name: "Cambo", value: "'Cambo', serif" },
    { name: "Cantata One", value: "'Cantata One', serif" },
    { name: "Cardo", value: "'Cardo', serif" },
    { name: "Castoro", value: "'Castoro', serif" },
    { name: "Caudex", value: "'Caudex', serif" },
    { name: "Cinzel", value: "'Cinzel', serif" },
    { name: "Copse", value: "'Copse', serif" },
    { name: "Cormorant", value: "'Cormorant', serif" },
    { name: "Cormorant Garamond", value: "'Cormorant Garamond', serif" },
    { name: "Cormorant Infant", value: "'Cormorant Infant', serif" },
    { name: "Cormorant SC", value: "'Cormorant SC', serif" },
    { name: "Cormorant Unicase", value: "'Cormorant Unicase', serif" },
    { name: "Cormorant Upright", value: "'Cormorant Upright', serif" },
    { name: "Coustard", value: "'Coustard', serif" },
    { name: "Crete Round", value: "'Crete Round', serif" },
    // { name: "Crimson Pro", value: "'Crimson Pro', serif" },
    { name: "Crimson Text", value: "'Crimson Text', serif" },
    { name: "Cutive", value: "'Cutive', serif" },
    // { name: "David Libre", value: "'David Libre', serif" },
    { name: "Della Respira", value: "'Della Respira', serif" },
    { name: "DM Serif Display", value: "'DM Serif Display', serif" },
    { name: "DM Serif Text", value: "'DM Serif Text', serif" },
    { name: "Domine", value: "'Domine', serif" },
    { name: "Donegal One", value: "'Donegal One', serif" },
    { name: "EB Garamond", value: "'EB Garamond', serif" },
    { name: "Eczar", value: "'Eczar', serif" },
    { name: "Enriqueta", value: "'Enriqueta', serif" },
    { name: "Esteban", value: "'Esteban', serif" },
    { name: "Fanwood Text", value: "'Fanwood Text', serif" },
    { name: "Fauna One", value: "'Fauna One', serif" },
    { name: "Faustina", value: "'Faustina', serif" },
    { name: "Fenix", value: "'Fenix', serif" },
    { name: "Fjord One", value: "'Fjord One', serif" },
    { name: "Frank Ruhl Libre", value: "'Frank Ruhl Libre', serif" },
    // { name: "Fraunces", value: "'Fraunces', serif" },
    { name: "Gabriela", value: "'Gabriela', serif" },
    { name: "Gelasio", value: "'Gelasio', serif" },
    // { name: "Gentium Basic", value: "'Gentium Basic', serif" },
    // { name: "Gentium Book Basic", value: "'Gentium Book Basic', serif" },
    { name: "Gilda Display", value: "'Gilda Display', serif" },
    { name: "Glegoo", value: "'Glegoo', serif" },
    // { name: "Goudy Bookletter 1911", value: "'Goudy Bookletter 1911', serif" },
    { name: "Grenze", value: "'Grenze', serif" },
    { name: "Gupter", value: "'Gupter', serif" },
    { name: "Gurajada", value: "'Gurajada', serif" },
    { name: "Habibi", value: "'Habibi', serif" },
    { name: "Halant", value: "'Halant', serif" },
    { name: "Headland One", value: "'Headland One', serif" },
    // { name: "Hepta Slab", value: "'Hepta Slab', serif" },
    // { name: "Holtwood One SC", value: "'Holtwood One SC', serif" },
    { name: "Ibarra Real Nova", value: "'Ibarra Real Nova', serif" },
    { name: "IBM Plex Serif", value: "'IBM Plex Serif', serif" },
    // { name: "IM Fell Double Pica", value: "'IM Fell Double Pica', serif" },
    // {
    //     name: "IM Fell Double Pica SC",
    //     value: "'IM Fell Double Pica SC', serif",
    // },
    // { name: "IM Fell DW Pica", value: "'IM Fell DW Pica', serif" },
    // { name: "IM Fell DW Pica SC", value: "'IM Fell DW Pica SC', serif" },
    // { name: "IM Fell English", value: "'IM Fell English', serif" },
    // { name: "IM Fell English SC", value: "'IM Fell English SC', serif" },
    // { name: "IM Fell French Canon", value: "'IM Fell French Canon', serif" },
    // {
    //     name: "IM Fell French Canon SC",
    //     value: "'IM Fell French Canon SC', serif",
    // },
    // { name: "IM Fell Great Primer", value: "'IM Fell Great Primer', serif" },
    // {
    //     name: "IM Fell Great Primer SC",
    //     value: "'IM Fell Great Primer SC', serif",
    // },
    // { name: "Imbue", value: "'Imbue', serif" },
    { name: "Inika", value: "'Inika', serif" },
    { name: "Inknut Antiqua", value: "'Inknut Antiqua', serif" },
    { name: "Inria Serif", value: "'Inria Serif', serif" },
    { name: "Italiana", value: "'Italiana', serif" },
    { name: "Jacques Francois", value: "'Jacques Francois', serif" },
    { name: "Jomolhari", value: "'Jomolhari', serif" },
    { name: "Josefin Slab", value: "'Josefin Slab', serif" },
    { name: "Judson", value: "'Judson', serif" },
    { name: "Junge", value: "'Junge', serif" },
    { name: "Kadwa", value: "'Kadwa', serif" },
    { name: "Kameron", value: "'Kameron', serif" },
    { name: "Karma", value: "'Karma', serif" },
    { name: "Kotta One", value: "'Kotta One', serif" },
    { name: "Kreon", value: "'Kreon', serif" },
    { name: "Kurale", value: "'Kurale', serif" },
    { name: "Ledger", value: "'Ledger', serif" },
    { name: "Libre Baskerville", value: "'Libre Baskerville', serif" },
    { name: "Libre Caslon Display", value: "'Libre Caslon Display', serif" },
    { name: "Libre Caslon Text", value: "'Libre Caslon Text', serif" },
    { name: "Linden Hill", value: "'Linden Hill', serif" },
    // { name: "Literata", value: "'Literata', serif" },
    { name: "Lora", value: "'Lora', serif" },
    { name: "Lusitana", value: "'Lusitana', serif" },
    { name: "Lustria", value: "'Lustria', serif" },
    { name: "Maitree", value: "'Maitree', serif" },
    { name: "Manuale", value: "'Manuale', serif" },
    { name: "Marcellus", value: "'Marcellus', serif" },
    { name: "Marcellus SC", value: "'Marcellus SC', serif" },
    // { name: "Markazi Text", value: "'Markazi Text', serif" },
    { name: "Marko One", value: "'Marko One', serif" },
    { name: "Martel", value: "'Martel', serif" },
    { name: "Mate", value: "'Mate', serif" },
    { name: "Mate SC", value: "'Mate SC', serif" },
    { name: "Merriweather", value: "'Merriweather', serif" },
    { name: "Montaga", value: "'Montaga', serif" },
    { name: "Nanum Myeongjo", value: "'Nanum Myeongjo', serif" },
    { name: "Neuton", value: "'Neuton', serif" },
    // { name: "Newsreader", value: "'Newsreader', serif" },
    { name: "Noticia Text", value: "'Noticia Text', serif" },
    { name: "Noto Serif", value: "'Noto Serif', serif" },
    // { name: "Noto Serif JP", value: "'Noto Serif JP', serif" },
    // { name: "Noto Serif KR", value: "'Noto Serif KR', serif" },
    // { name: "Noto Serif SC", value: "'Noto Serif SC', serif" },
    // { name: "Noto Serif TC", value: "'Noto Serif TC', serif" },
    // { name: "Old Standard TT", value: "'Old Standard TT', serif" },
    { name: "Oranienbaum", value: "'Oranienbaum', serif" },
    { name: "Ovo", value: "'Ovo', serif" },
    { name: "Peddana", value: "'Peddana', serif" },
    { name: "Petrona", value: "'Petrona', serif" },
    { name: "Piazzolla", value: "'Piazzolla', serif" },
    { name: "Playfair Display", value: "'Playfair Display', serif" },
    { name: "Playfair Display SC", value: "'Playfair Display SC', serif" },
    { name: "Podkova", value: "'Podkova', serif" },
    { name: "Poly", value: "'Poly', serif" },
    // { name: "Port Lilgat Slab", value: "'Port Lilgat Slab', serif" },
    { name: "Prata", value: "'Prata', serif" },
    { name: "Pridi", value: "'Pridi', serif" },
    { name: "Prociono", value: "'Prociono', serif" },
    { name: "PT Serif", value: "'PT Serif', serif" },
    { name: "PT Serif Caption", value: "'PT Serif Caption', serif" },
    { name: "Quando", value: "'Quando', serif" },
    { name: "Quattrocento", value: "'Quattrocento', serif" },
    { name: "Radley", value: "'Radley', serif" },
    { name: "Ramaraja", value: "'Ramaraja', serif" },
    { name: "Rasa", value: "'Rasa', serif" },
    { name: "Rhodium Libre", value: "'Rhodium Libre', serif" },
    { name: "Roboto Slab", value: "'Roboto Slab', serif" },
    { name: "Rokkitt", value: "'Rokkitt', serif" },
    { name: "Rosarivo", value: "'Rosarivo', serif" },
    { name: "Rozha One", value: "'Rozha One', serif" },
    { name: "Sahitya", value: "'Sahitya', serif" },
    { name: "Rufina", value: "'Rufina', serif" },
    { name: "Sanchez", value: "'Sanchez', serif" },
    { name: "Scheherazade", value: "'Scheherazade', serif" },
    { name: "Scope One", value: "'Scope One', serif" },
    { name: "Shippori Mincho", value: "'Shippori Mincho', serif" },
    { name: "Shippori Mincho B1", value: "'Shippori Mincho B1', serif" },
    { name: "Slabo 13px", value: "'Slabo 13px', serif" },
    { name: "Slabo 27px", value: "'Slabo 27px', serif" },
    { name: "Solway", value: "'Solway', serif" },
    { name: "Song Myung", value: "'Song Myung', serif" },
    { name: "Sorts Mill Goudy", value: "'Sorts Mill Goudy', serif" },
    { name: "Source Serif Pro", value: "'Source Serif Pro', serif" },
    { name: "Spectral", value: "'Spectral', serif" },
    { name: "Spectral SC", value: "'Spectral SC', serif" },
    { name: "Sree Krushnadevaraya", value: "'Sree Krushnadevaraya', serif" },
    { name: "Stoke", value: "'Stoke', serif" },
    { name: "Suez One", value: "'Suez One', serif" },
    { name: "Sumana", value: "'Sumana', serif" },
    { name: "Sura", value: "'Sura', serif" },
    { name: "Suranna", value: "'Suranna', serif" },
    { name: "Suravaram", value: "'Suravaram', serif" },
    { name: "Taviraj", value: "'Taviraj', serif" },
    { name: "Texturina", value: "'Texturina', serif" },
    { name: "Tienne", value: "'Tienne', serif" },
    { name: "Tinos", value: "'Tinos', serif" },
    { name: "Trirong", value: "'Trirong', serif" },
    { name: "Trocchi", value: "'Trocchi', serif" },
    { name: "Trykker", value: "'Trykker', serif" },
    { name: "Ultra", value: "'Ultra', serif" },
    { name: "Unna", value: "'Unna', serif" },
    { name: "Vesper Libre", value: "'Vesper Libre', serif" },
    { name: "Vidaloka", value: "'Vidaloka', serif" },
    { name: "Volkhov", value: "'Volkhov', serif" },
    // { name: "Vollkorn", value: "'Vollkorn', serif" },
    { name: "Vollkorn SC", value: "'Vollkorn SC', serif" },
    { name: "Yrsa", value: "'Yrsa', serif" },
    { name: "ZCOOL XiaoWei", value: "'ZCOOL XiaoWei', serif" },
    { name: "Zilla Slab", value: "'Zilla Slab', serif" },
];
